---
- hosts: droplet
  remote_user: "{{ user_sysadmin_name }}"
  roles:
    - role: git-clone
      clone_repository: "{{ pixelcloud_apps_repository }}"
      clone_directory: "{{ root_dir_apps }}/pixelcloud"
      clone_user: "{{ user_admin_name }}"

    - role: ssl
      become: yes
      become_user: "{{ user_admin_name }}"

    - role: docker-network
      docker_network_name: "{{ app_nginx_proxy_network_name }}"
      docker_network_driver: "{{ app_nginx_proxy_network_driver }}"

    - role: service
      service_user_name: "{{ user_admin_name }}"
      service_group_name: "{{ group_www_name }}"
      service_name: "app-pixelcloud-nginx_proxy"
      service_dir: "{{ root_dir_apps }}/pixelcloud/nginx-proxy"
      service_description: "Watches docker containers that contains sites and automatically adds them to reverse proxy."
