---
- name: "Register service {{ service_name }}"
  become: yes
  become_user: root
  template: src=service.j2 dest="/etc/init/{{ service_name }}.conf" owner=root group=root mode=0644

- name: "Start service {{ service_name }}"
  become: yes
  become_user: root
  service: name="{{ service_name }}" state=started
